services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/instance
      - /app/__pycache__

    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    environment:
      - VITE_API_URL=http://localhost:5001
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  sqlite_data:
