# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dialogueHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://team26.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e517434c0e864c4a9aeeb13ccec42f06 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a94ca868affa4d4baf4040317b9a8786 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: team26.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e517434c0e864c4a9aeeb13ccec42f06 }}/frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dialogueHub'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e7483ab8e45a49cb9118ee35158d071b }}
        images: 'team26.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e517434c0e864c4a9aeeb13ccec42f06 }}/frontend:${{ github.sha }}'